name: tea
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#469CBF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
    - assets/data/
