name: tea
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  fonts:
    - family: Odin
      fonts:
        - asset: assets/fonts/Odin.otf