// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzFnDUPcde_wGoaxd3wrh53UYUDgQkCI',
    appId: '1:70507233363:web:13f6e69bc254cb2d4286a6',
    messagingSenderId: '70507233363',
    projectId: 'appautismo-5daeb',
    authDomain: 'appautismo-5daeb.firebaseapp.com',
    storageBucket: 'appautismo-5daeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKlroZJVEMUdqti6jyrrbMZt7W25q0bGs',
    appId: '1:70507233363:android:48aa92f5018987374286a6',
    messagingSenderId: '70507233363',
    projectId: 'appautismo-5daeb',
    storageBucket: 'appautismo-5daeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0561VDBxHCTGSEXylcbP-Y-ZfPl1OyK4',
    appId: '1:70507233363:ios:e558522f5c51a4974286a6',
    messagingSenderId: '70507233363',
    projectId: 'appautismo-5daeb',
    storageBucket: 'appautismo-5daeb.appspot.com',
    iosBundleId: 'com.example.tea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0561VDBxHCTGSEXylcbP-Y-ZfPl1OyK4',
    appId: '1:70507233363:ios:8a4f4c39d0d0d15f4286a6',
    messagingSenderId: '70507233363',
    projectId: 'appautismo-5daeb',
    storageBucket: 'appautismo-5daeb.appspot.com',
    iosBundleId: 'com.example.tea.RunnerTests',
  );
}
